### ISSUE TITLE
How can one cite this dynamic review?

### ISSUE THREAD

**Issue by vd4mmind** [greenelab/deep-review#1018]
Is it possible to cite this dynamic review? If so how? I am a bit unable to figure out from the GitHub page. There are a few DOI but are they all needed to be cited? Or is it still advisable to put 2018 one?

Kind regards,

Vivek

**Comment by agitter** [comment]
Because most of the content is from the 2018 journal publication, I currently recommend that for most citations:
> Ching T, Himmelstein DS, Beaulieu-Jones BK, Kalinin AA, Do BT, Way GP, Ferrero E, Agapow P-M, Zietz M, Hoffman MM, Xie W, Rosen GL, Lengerich BJ, Israeli J, Lanchantin J, Woloszynek S, Carpenter AE, Shrikumar A, Xu J, Cofer EM, Lavender CA, Turaga SC, Alexandari AM, Lu Z, Harris DJ, DeCaprio D, Qi Y, Kundaje A, Peng Y, Wiley LK, Segler MHS, Boca SM, Swamidass SJ, Huang A, Gitter A, and Greene CS. 2018. Opportunities and obstacles for deep learning in biology and medicine. Journal of The Royal Society Interface 15(141):20170387. doi:10.1098/rsif.2017.0387

I'm not sure how to best cite the current version of Deep Review 2.0 if you're referencing the new sections.  The author order changes every build.  You could do something like:
> (current author order from https://greenelab.github.io/deep-review/#version-2.0-authors), The Version 1.0 Deep Review Authors. 2020. Opportunities and obstacles for deep learning in biology and medicine. Manubot https://greenelab.github.io/deep-review/v/081fb466dd13c2813b3ae14bb916173f5d0442c5/

The URL https://greenelab.github.io/deep-review/v/081fb466dd13c2813b3ae14bb916173f5d0442c5/ comes from the _permalink_ link at the top of https://greenelab.github.io/deep-review/  That will point to the specific version you accessed, which could be important because the author list and content will change.

@dhimmel any better ideas regarding citing the work in progress?

**Comment by dhimmel** [comment]
> any better ideas regarding citing the work in progress?

No, I agree with your advice.

If you want to cite the version of the manuscript that you see online, find the permalink and use that URL. And then I'd use the metadata (author list) corresponding to that version of the manuscript.

**Comment by vd4mmind** [comment]
Thank you both for the response. Appreciate it.
I have used the above link mentioned. Let's see what the reviewers say about it. Thanks for the heads up. I hope it gets accepted and does not ask me to point the published version 1 since I specifically want a section from the dynamic review to be referenced that has done a better job than me in explaining the context I am referring to. :)
