### ISSUE TITLE
Tabulation of papers discussed so far

### ISSUE THREAD

**Issue by traversc** [greenelab/deep-review#119]
I put together a compilation of all the papers discussed so far and extracted several attributes: https://docs.google.com/spreadsheets/d/1gO5BHzdXLvwZtiiqNtXx7w7JS8o1LYtCsKRBpY1N_TM/edit?usp=sharing

Currently, it is sorted by number of citations.  Perhaps this could be helpful to prioritize which papers to discuss in the review?

**Comment by cgreene** [comment]
@traversc : Thanks for putting this together! I think that having a tabulated form of the papers that have received discussion is helpful. I feel quite strongly that we shouldn't prioritize papers based on the number of citations. I'd rather focus on papers that inform our guiding question. This may help to elevate discussion around papers that were previously missed if they are particularly relevant to our topic and informative. Since our review structure is not just a literature survey, I think that our guiding question (which I hope that we will put together an opinionated guess on in the conclusion) should be most central to what we decide to discuss.

**Comment by agitter** [comment]
@traversc It could be helpful to think about what conclusions you would hope to draw from annotating these papers before you spend substantial time working on it.  This collection of papers is not exhaustive, so we many not be able to assert things like "area *X* is understudied" unless we do a more systematic literature search.

If it would be helpful, I can also add labels to the GitHub issues (especially Categorize/Treat/Study) if you have suggested classifications.

**Comment by agitter** [comment]
We've been adding new papers and not maintaining this list, so I'm closing the issue.  Reopen if there is a strong need for it.
