### ISSUE TITLE
Integrative Data Analysis of Multi-Platform Cancer Data with a Multimodal Deep Learning Approach

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#14]
http://dx.doi.org/10.1109/TCBB.2014.2377729

**Comment by gwaygenomics** [comment]
Cool example of using deep learning to integrate information from different genomic platforms

### Biology
* Group ovarian cancer patients into subtypes by integrating gene expression, DNA methylation, and miRNA expression modalities. 
* Group breast cancer patients into subtypes by integrating gene expression and clinical information.
* Observe how concordant groupings are based on survival, treatment strategies, and other known grouping standards (such as [70 gene panel](http://www.nature.com/nature/journal/v415/n6871/full/415530a.html))

### Computational aspects

* Multimodal deep belief network
  * Stacked gaussian restricted boltzmann machines (gRBM)
  * Trained via [contrastive divergence](http://www.cs.toronto.edu/~fritz/absps/nccd.pdf)
* Modalities integrated via stacking hidden layers
  * Additional gRBM from single hidden layers to unified output layer

### Results

* Identify 8 ovarian cancer subtypes
  * Some with different survival and treatment strategies
* Identify 4 breast cancer subtypes
  * Differential survival

### Concerns

* Output layer of network determines how many subtypes are found (`k`)
  * No real discussion about how to determine `k` other than optimizing MSE across raw number of params
    * Severely uneven class assignment
* Comparison to k-means in ovarian data
  * Simply because it separates out survival differences better does not necessarily mean deep belief network is better
* Overfitting 
  * Could attempt to apply network to other existing datasets 
  * Could compare subtype labels to existing labels

**Comment by cgreene** [comment]
Discussion seems to have stopped, but this is clearly a categorization paper. Adding there. #93

**Comment by cgreene** [comment]
@gwaygenomics : I will leave to you whether or not we want to talk about this in categorize. If we want to, it could help to bring #157 back into the section. I think that the gene expression bit of categorize is the area we have the least evidence on right now. I don't know if it's enough to have an effective subsection.
