### ISSUE TITLE
Understanding sequence conservation with deep learning

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#217]
https://doi.org/10.1101/103929

> Motivation: Comparing the human genome to the genomes of closely related mammalian species has been a powerful tool for discovering functional elements in the human genome. Millions of conserved elements have been discovered. However, understanding the functional roles of these elements still remain a challenge, especially in noncoding regions. In particular, it is still unclear why these elements are evolutionarily conserved and what kind of functional elements are encoded within these sequences. Results: We present a deep learning framework, called DeepCons, to uncover potential functional elements within conserved sequences. DeepCons is a convolutional neural net (CNN) that receives a short segment of DNA sequence as input and outputs the probability of the sequence of being evolutionary conserved. DeepCons utilizes hundreds of convolution kernels to detect features within DNA sequences, and automatically learns these kernels after training the CNN model using 887,577 conserved elements and a similar number of nonconserved elements in the human genome. On a balanced test dataset, DeepCons can achieve an accuracy of 75% in determining whether a sequence element is conserved or not, and the area under the ROC curve of 0.83, based on information from the human genome alone. We further investigate the properties of the learned kernels. Some kernels are directly related to well-known regulatory motifs corresponding to transcription factors. Many kernels show positional biases relative to transcriptional start sites or transcription end sites. But most of discovered kernels do not correspond to any known functional element, suggesting that they might represent unknown categories of functional elements. We also utilize DeepCons to annotate how changes at each individual nucleotide might impact the conservation properties of the surrounding sequences. Availability: The source code of DeepCons and all the learned convolution kernels in motif format is publicly available online at https://github.com/uci-cbcl/DeepCons.

I don't plan to discuss this but will leave it open for a little while in case someone else wants to make a case that we should.

**Comment by akundaje** [comment]
Just a few things to note

- Flawed trivial negative set (randomly sampled from the genome) with
flawed evaluation - AuROC on balanced data.
- likely under capacity model. One Conv layer and 1 dense likely used to
try to interpret filters. Deeper models on a less trivial negative set
would do better than this architecture but have even less interpretable
filters.
- Overinterpretation of filters. Often a large number of neurons in a
neural network end up doing nothing (this can be easily tested) or capture
partially redundant patterns which is why the net can often be heavily
compressed with no loss in accuracy. Here every filter is being assumed to
be some motif or some predictive pattern. Most are likely doing nothing or
learning trivial dinucleotide content. Thought experiment - what if I used
2000 instead of 1000 filters. Would I interpret all of them as being
important patterns? Again this is not hard to evaluate.

**Comment by agitter** [comment]
@akundaje would you suggest I leave this open so you can include it in the interpretation/evaluation discussion?

**Comment by akundaje** [comment]
No. You can close it.  There are published high profile papers that have
these flaws that I'll point to.
