### ISSUE TITLE
Push Access

### ISSUE THREAD

**Issue by blengerich** [greenelab/deep-review#311]
Hi @cgreene and @agitter, I'd like to push a subsection to a new branch, but am getting a 403 error:

 $ git push origin treat_categorize
Username for 'https://github.com': blengerich
Password for 'https://blengerich@github.com': 
remote: Permission to greenelab/deep-review.git denied to blengerich.
fatal: unable to access 'https://github.com/greenelab/deep-review.git/': The requested URL returned error: 403

Could you please open the commit access, and lock the master branch instead? Thanks.

**Comment by agitter** [comment]
If you create a fork with your username, then you can push to that fork.
Once you push, the GitHub website will show an option to create a pull
request. We'll discuss and review it with you and then merge.


On Apr 13, 2017 6:29 PM, "Ben Lengerich" <notifications@github.com> wrote:

Hi @cgreene <https://github.com/cgreene> and @agitter
<https://github.com/agitter>, I'd like to push a subsection to a new
branch, but am getting a 403 error:

$ git push origin treat_categorize
Username for 'https://github.com': blengerich
Password for 'https://blengerich@github.com':
remote: Permission to greenelab/deep-review.git denied to blengerich.
fatal: unable to access 'https://github.com/greenelab/deep-review.git/':
The requested URL returned error: 403

Could you please open the commit access, and lock the master branch
instead? Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/greenelab/deep-review/issues/311>, or mute the thread

**Comment by blengerich** [comment]
Ah, thank you!
