### ISSUE TITLE
Exploring the ChestXray14 dataset: problems

### ISSUE THREAD

**Issue by brettbj** [greenelab/deep-review#722]
https://lukeoakdenrayner.wordpress.com/2017/12/18/the-chestxray14-dataset-problems/

I don’t want to bury the lede here, so I will say this up front. I believe the ChestXray14 dataset, as it exists now, is not fit for training medical AI systems to do diagnostic work. To set my argument out clearly, there are specific problems I want to discuss with:

how accurate the labels are
what the labels actually mean, medically
how useful the labels are for image analysis

This should be at least discussed here and/or mentioned/considered in the categorize section. I believe this was originally written by @yfpeng so it would be good to get follow up thoughts. I'll tag @alxndrkalinin @cgreene and @agitter since they also had edits here. 

related to #709

**Comment by brettbj** [comment]
I agree with the vast majority of Luke's post. In general, it may be useful to develop methods that expect and are robust to some level of uncertainty (multiple images per patient, lab tests that condition an image etc.). I do think it's useful to examine situations where a diagnosis was made even if the image may not hold the information to support this diagnosis. This is a challenge that allows for a more realistic evaluation of the capabilities of DL. Too many evaluations are done on very carefully curated datasets that are far from operational reality. 

BUT... we shouldn't conflate these to the main point of Luke's work where he is finding that there may have been a systematic issue with labelling and images are incorrectly labelled.

**Comment by agitter** [comment]
@brettbj I agree that it would be a good idea to discuss this.  @yfpeng may have a diverging opinion, which I'm also interested in hearing, but I think we can come to a good consensus about what we want to say in the review.  Do you plan to make a pull request with a specific suggestion?

The imaging section of Categorize and parts of Discussion could be good places to mention this.  Also feel welcome to cite Luke's post so that we don't have to re-state points he already made.

**Comment by akundaje** [comment]
We should make sure the discussion around this paper is about the
importance of sanity checks and careful curation of data fed to ANY
learning algorithm. This is not a problem with deep learning. There is
already misdirected criticism being thrown around based on this incident at
how AI/deep learning is flawed. This is a data quality problem. Not a
learning algorithm problem.

This is not even a subtle problem like implicit bias which algorithms and
datasets should take into account and try to correct. This seems more like
a pretty egregious lack of some pretty obvious sanity checks (looking at
the images!) and poor label quality. Of course the authors of the
paper/dataset might disagree. I'm interested in their official response.

Seems like the main conclusions to be drawn from this particular issue is
that data curators need to be more careful, ML folks need to be far more
skeptical of data quality, ML folks need to collaborate more with domain
experts for sanity checking input data and output result/conclusions before
making hyped claims, AI will very much require radiologists/domain experts
to curate high quality datasets and help flag confounders. Models will only
be as good or worse than the data they are trained on, irrespective of
whether it's deep learning or not.

**Comment by cgreene** [comment]
@akundaje : sure - I agree that this isn't an algorithm but is a use situation. I think a very real issue is that if we avoid discussing some of these nuances (the need to _look at predictions with an expert_) then we may miss an important duty of our paper for CS readers. I think the view that if you run your approach and get high AUC/accuracies then everything is working may be relatively widespread _outside of those already working in the biomedical space_. It's possible it also has some hold in bio/medicine. I nearly always include something saying "this stuff isn't magic / you still need to think" in my talks. I think making sure a similar message makes it into the paper is worth doing.

**Comment by akundaje** [comment]
Oh yeah. I'm all in favor of including this issue in the review.

**Comment by yfpeng** [comment]
### This is not an "official response"

First, I want to thank @brettbj and @akundaje for bringing this topic to my attention.  I cannot agree more that we "need to collaborate more with domain experts" and I believe that's one of the main reasons we are here to write this review together. I also agree with @akundaje that we need more and more radiologists to curate high quality detests, and, more **importantly**, encourage them to *share* the dataset. 

As for the ChestXray14 dataset, we have over 100,000 unlabeled images with radiology reports. It is quite challenging to ask radiologists to manually label all of them. Instead, with the hope to benefit the community quickly, we applied a text-mining pipeline to extract labels from the reports corresponding to the images. Specifically, we first used a widely-used named entity recognition and normalization tool (MetaMap) to detect labels from the reports. Then we filtered negative and uncertain labels using rules. By this way, we obtained the text-mined document-level labels for each image. I understand this pipeline is not perfect because each step will bring errors, but it is one of the state-of-the-art methods we have so far. And we have applied this method to 4 independent corpora to evaluate its generalizability. 

This dataset is probably the first released data of such a large size with "text-mined" labels. I do hope our efforts will benefit the scientific community. We will continually improve its quality in future. If Luke is willing to send me image IDs with his labels, I am more than happy to analyze these cases, reconcile his results, and improve our method.

The thought @brettbj and @akundaje sharing here definitely help me in the future. I am also interested to see @akundaje 's discussion in the review and learn more from his valuable suggestions. 

Of course, other constructive criticisms and suggestions are always welcomed.

**Comment by akundaje** [comment]
Yifan - thanks for your thoughts and response.

Medical imaging is very far from my domain of expertise so I will let
others who are experts comment on this issue in the review.

Just wanted to say that I totally understand how difficult an undertaking
this must have been to collect and release such a massive dataset. I think
it's very commendable that this dataset was made available. I also
sympathize with how much burden there is on data curators to release high
quality datasets. It's often impossible to get it right the first
time. Training
an ML algorithm on high quality data is often the easiest part of the
prediction pipeline. The importance and difficulty of generating high
quality data is definitely greatly under appreciated.

My point was simply that in the context of a review on deep learning for
biomedicine, we describe this particular example to motivate the importance
of high quality data and close interaction with domain experts. I think we
are all on the same page.

Thanks
Anshul.

**Comment by alxndrkalinin** [comment]
I agree with Anshul, it's worth discussing as a data quality challenge and we should mention that it is important to emphasize dataset limitations on its release. I can try to come up with a draft by the end of the week if no one does it earlier.

**Comment by cgreene** [comment]
I think this is a good opportunity to highlight the need for data sharing in this domain. Without the shared data, this could have become one of the numerous other papers that claim great results but are unverifiable. We should view claims from papers without full sharing with a _very high_ amount of skepticism.

Note that similar concerns exist around AlphaZero releasing just 10 games (plus some other issues): https://medium.com/@josecamachocollados/is-alphazero-really-a-scientific-breakthrough-in-ai-bf66ae1c84f2

**Comment by yfpeng** [comment]
I will rephrase the chest x-ray paragraph. I would like to leave the discussion of a data quality challenge to others, particularly for this chest x-ray14 dataset, because of the potential conflicts of interest.
